name: Mirror to codeberg
on:
  push:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Mirror to Codeberg
        run: |
          git fetch --unshallow
          git remote add codeberg https://visnk:${{secrets.CBERG_TOKEN}}@codeberg.org/visnk/appstore.git
          git push 